### ISSUE TITLE
Traceback & TypeError when "Scraping Paid Content"

### ISSUE THREAD

**Issue by nicknaym** [DIGITALCRIMINAL/UltimaScraper#1570]
Hi all, as the title mentions, I'm getting a slew of positional TypeErrors before I even get a chance to initiate the download part of the script. [https://i.ibb.co/Jrh6Z7r/Screenshot-2021-08-12-104228.png](url)

Any tips or assistance is appreciated, I'm pretty green when it comes to this sort of thing but I can follow along.
![Screenshot 2021-08-12 104228](https://user-images.githubusercontent.com/88808133/129121397-7ac72242-c7bb-449e-a6c4-20aaca688f64.png)

**Comment by shixel** [comment]
I'm seeing the same error.

**Comment by americanseeder1865** [comment]
What is your tqdm version?

**Comment by Throwaway115** [comment]
im not sure if i have the same issue or not, but im now getting this since i updated the script today

![image](https://user-images.githubusercontent.com/77456400/129234591-e73ee5ad-1bbc-47ab-8bb8-0d8a3adf4e89.png)

**Comment by horatiorosa** [comment]
I am having the same issues as well. I updated `tqdm` via `pip3` and still get a similar errors
```
Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/src/app/./start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "/usr/src/app/datascraper/main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "/usr/src/app/modules/onlyfans.py", line 401, in paid_content_scraper
    unrefined_set = await tqdm.gather(tasks, **settings)
  File "/usr/local/lib/python3.9/site-packages/tqdm/asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "/usr/local/lib/python3.9/site-packages/tqdm/asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/usr/local/lib/python3.9/site-packages/tqdm/asyncio.py", line 76, in wrap_awaitable
    return i, await f
TypeError: object list can't be used in 'await' expression
```
Does anyone know how to set a default download profile? Script seems to trip when scraping a specific profile. Maybe I can skip that profile and scrape the others? 
![Screen Shot 2021-08-13 at 1 00 12 PM](https://user-images.githubusercontent.com/11340947/129394122-0adeacb1-dd37-4eab-bd88-0c8f9eb3e407.png)

**Comment by somjelly1** [comment]
![Screenshot 2021-08-16 142829](https://user-images.githubusercontent.com/10469777/129612214-bdc3041e-d441-417f-b7d6-4db3f29c6968.png)

I think i am having a similar issue

**Comment by horatiorosa** [comment]
@somjelly1  take a look at this thread, _maybe_ it might help you. [issue#1561](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1561#issuecomment-899094042)

**Comment by bigbluedeer** [comment]
initial error is possible duplicate of #1527 and #1577
